ARG base_image

FROM opensearchproject/opensearch:2.12.0 as opensearch

# ok, this is a little weird.
# we're building this image to run on Cloud Foundry, where we can
# only have one port exposed. The upstream exposes more than one,
# and docker doesn't provide a direct method to override it.
# so, we're using the opensearch image as a "builder" and then copying
# everything into the base hardened image ¯\_(ツ)_/¯
FROM ${base_image}

COPY --from=opensearch /usr/share/opensearch /usr/share/opensearch

ARG UID=1000
ARG GID=1000
ARG OPENSEARCH_HOME=/usr/share/opensearch

ENV PATH $PATH:$OPENSEARCH_HOME/bin

# add the new stuff
COPY docker/opensearch/config.yml ${OPENSEARCH_HOME}/config/opensearch-security/config.yml
COPY docker/opensearch/roles.yml ${OPENSEARCH_HOME}/config/opensearch-security/roles.yml
COPY docker/opensearch/roles_mapping.yml ${OPENSEARCH_HOME}/config/opensearch-security/roles_mapping.yml

WORKDIR $OPENSEARCH_HOME

# Change user
USER $UID
EXPOSE 9200

ENTRYPOINT ["./opensearch-docker-entrypoint.sh"]
# Dummy overridable parameter parsed by entrypoint
CMD ["opensearch"]
