---
cf_user:
  reserved: false
  hidden: false
  cluster_permissions:
  - "read"
  - "cluster:monitor/nodes/stats"
  - "cluster:monitor/task/get"
  index_permissions:
  - index_patterns:
    - "logs-app-*"
    fls:
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: false
_meta:
  type: "roles"
  config_version: 2
