#!/usr/bin/env bash

set -euxo pipefail
shopt -s inherit_errexit 2>/dev/null || true

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
python=${dir}/venv/bin/python
usage() {
  local me
  me=$(basename "$0")
  
  cat <<-EOF

  USAGE: ${me} COMMAND

  Run development workflows.

  Examples:

    # Run the tests once
    ${me}

    # same as above
    ${me} tests

    # install dev dependencies in a local virtualenv
    ${me} set-up-environment

    # add new required packages from requirements.in to requirements.txt
    ${me} update-requirements

    # upgrade versions for requirements
    ${me} upgrade-requirements

    # upgrade version for specific requirement
    ${me} upgrade-requirements <requirement>

    # run flask locally, (Bring Your Own [UAA, CF, opensearch_dashboards])
    ${me} serve

    # run a local Opensearch + Opensearch Dashboards cluster in docker-compose
    ${me} cluster

    # destroy cluster created above
    ${me} destroy-cluster

    # push Opensearch/Dashboards/Proxy cluster to CF (make sure you update cf/secrets.yml first)
    ${me} cf

    # run e2e tests
    ${me} e2e


EOF
}

pushd () {
  # make pushd silent
  command pushd "$@" > /dev/null
}

popd () {
  # make popd silent
  command popd > /dev/null
}

update_requirements() {
  export CUSTOM_COMPILE_COMMAND="./dev update-requirements"
  $python -m piptools compile \
    --quiet \
    --output-file=requirements.txt \
    pip-tools/requirements.in
   $python -m piptools compile \
    --quiet \
    --output-file=dev-requirements.txt \
    pip-tools/dev-requirements.in
}

set_up_ci_environment () {
  python3 -m venv venv
  # we need to update pip because the version from apt is too old, and breaks
  # when we try to install from requirements files later
  ${python} -m pip install --upgrade pip
  # do this first to make sure we have piptools
  ${python} -m pip install -r dev-requirements.txt
  # do this again for syncs that might involve deletions
  ${python} -m piptools sync requirements.txt dev-requirements.txt
  ${python} -m playwright install firefox
}

set_up_environment () {
  python -m venv venv
  # do this first to make sure we have piptools
  ${python} -m pip install -r dev-requirements.txt
  # do this again for syncs that might involve deletions
  ${python} -m piptools sync requirements.txt dev-requirements.txt
  ${python} -m playwright install firefox
}

upgrade_requirements() {
  if [[ $# -ge 1 ]]; then
    if [[ $# -ge 2 ]]; then
      echo "can't update more than one package at a time"
    fi
    ${python} -m piptools compile --upgrade-package "$1" --output-file requirements.txt pip-tools/requirements.in
    ${python} -m piptools compile --upgrade-package "$1" --output-file dev-requirements.txt pip-tools/dev-requirements.in

  else
    ${python} -m piptools compile --upgrade --output-file requirements.txt pip-tools/requirements.in
    ${python} -m piptools compile --upgrade --output-file dev-requirements.txt pip-tools/dev-requirements.in
  fi
}

watch_tests() {
  export FLASK_ENV=unit
  ${python} -m piptools sync requirements.txt dev-requirements.txt
  ${python} -m pytest_watch --spool=1000 -n -c -w -- -Werror -vv tests "$@"
}

cf_push() {
  cf push -f cf/opensearch-manifest.yml --vars-file cf/secrets.yml
  cf push -f cf/opensearch-dashboards-manifest.yml --vars-file cf/secrets.yml
  cf push -f cf/proxy-manifest.yml --vars-file cf/secrets.yml
}

cf_network() {
  cf add-network-policy opensearch-dashboards opensearch --protocol tcp --port 9200
  cf add-network-policy auth-proxy opensearch-dashboards --protocol tcp --port 5601
}

main() {
  pushd "${dir}"
  trap popd exit
  local command=$1
  shift
  case $command in
    -h)
      usage
      ;;
    update-requirements|update-requirement)
      update_requirements "$@"
      ;;
    upgrade-requirements|upgrade_requirement)
      upgrade_requirements "$@"
      ;;
    set-up-ci-environment)
      set_up_ci_environment
      ;;
    set-up-environment|setup-environment)
      set_up_environment
      ;;
    test|tests)
      export FLASK_ENV=unit
      ${python} -m piptools sync requirements.txt dev-requirements.txt
      ${python} -m pytest tests
      ;;
    provision-cf-access)
      set -o allexport; source "${dir}/.env"; set +o allexport
      ./ci/provision-org-spaces.sh
      ;;
    serve)
      set -o allexport; source "${dir}/.env"; set +o allexport
      export FLASK_APP="opensearch_dashboards_cf_auth_proxy.app:create_app()"
      
      ${python} -m flask run -p "${PORT}"
      ;;
    cluster)
      
      pushd docker
        docker-compose up --force-recreate --build -d
      popd

      ;;
    destroy-cluster)
      pushd docker
        docker-compose down
      popd
      ;;
    cf-push)
      cf_push
      cf_network
      ;;
    cf-network)
      cf_network
      ;;
    watch-test|watch-tests)
      watch_tests "$@"
      ;;
    e2e)
      ${python} -m pytest e2e --browser firefox "$@"
      ;;
    e2e-local)
      set -o allexport; source "${dir}/.env"; set +o allexport
      bash ./ci/seed-es-data.sh
      ${python} -m pytest e2e --browser firefox "$@"
      ;;
    format)
      ${python} -m black .
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
