[build-system]
requires = ["setuptools >= 62.6", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.?venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
)/
'''
