FROM opensearchproject/opensearch-dashboards:2 AS opensearch-dashboards


FROM scratch

COPY --from=opensearch-dashboards / /

WORKDIR /usr/share/opensearch-dashboards

ENV PATH=/usr/share/opensearch-dashboards/bin:$PATH
USER 1000

EXPOSE 5601

COPY opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml

CMD ["/usr/local/bin/opensearch-dashboards"]
