FROM opensearchproject/opensearch-dashboards:2.12.0 AS opensearch-dashboards


FROM scratch

COPY --from=opensearch-dashboards / /

ARG OPENSEARCH_INITIAL_ADMIN_PASSWORD
ARG OPENSEARCH_DASHBOARDS_HOME=/usr/share/opensearch-dashboards
WORKDIR $OPENSEARCH_DASHBOARDS_HOME

ENV PATH=$OPENSEARCH_DASHBOARDS_HOME/bin:$PATH
USER 1000

EXPOSE 5601

COPY opensearch_dashboards.yml $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml

ENTRYPOINT ["./opensearch-dashboards-docker-entrypoint.sh"]
CMD ["opensearch-dashboards"]
