FROM opensearchproject/opensearch-dashboards:2 AS opensearch-dashboards


FROM scratch

COPY --from=opensearch-dashboards / /

ARG OPENSEARCH_DASHBOARDS_HOME=/usr/share/opensearch-dashboards
WORKDIR $OPENSEARCH_DASHBOARDS_HOME

ENV PATH=$OPENSEARCH_DASHBOARDS_HOME/bin:$PATH
USER 1000

EXPOSE 5601

ENTRYPOINT ["./opensearch-dashboards-docker-entrypoint.sh"]
CMD ["opensearch-dashboards"]
