FROM opensearchproject/opensearch:2 as opensearch

# ok, this is a little weird.
# we're building this image to run on Cloud Foundry, where we can
# only have one port exposed. The upstream exposes more than one, 
# and docker doesn't provide a direct method to override it.
# so, we're using the ODfE image as a "builder" and then copying
# everything into scratch, which is a blank image ¯\_(ツ)_/¯
FROM scratch

COPY --from=opensearch / /

# copying the files doesn't copy the metadata - that's the whole point
# these are the same as the upstream
WORKDIR /usr/share/opensearch
ENV JAVA_HOME /opt/jdk
ENV PATH $PATH:$JAVA_HOME/bin
ENV ELASTIC_CONTAINER true
USER 1000

# add the new stuff
COPY config.yml /usr/share/opensearch/plugins/opendistro_security/securityconfig/config.yml
COPY roles.yml /usr/share/opensearch/plugins/opendistro_security/securityconfig/roles.yml
COPY roles_mapping.yml /usr/share/opensearch/plugins/opendistro_security/securityconfig/roles_mapping.yml

EXPOSE 9200

ENTRYPOINT ["./opensearch-docker-entrypoint.sh"]
# Dummy overridable parameter parsed by entrypoint
CMD ["opensearch"]
