jobs:

- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [reconfigure]

    - task: test
      config:
        inputs: 
          - name: src
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: python
            tag: "3.8"
        run:
          path: src/ci/test.sh

- name: build-test-images
  plan:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [reconfigure]

    - put: dev-elasticsearch-image
      params:
        build: src/docker/elasticsearch
        dockerfile: src/docker/elasticsearch/dockerfile
        tag_as_latest: true
        cache: true

    - put: dev-kibana-image
      params:
        build: src/docker/kibana
        dockerfile: src/docker/kibana/dockerfile
        tag_as_latest: true
        cache: true

############################
#  RESOURCES

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: dev-elasticsearch-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image-elasticsearch-dev))

- name: dev-kibana-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image-kibana-dev))

############################
#  RESOURCE TYPES

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
